version: '3.8'

services:
  web:
    build: .
    container_name: fertilizer_flask_app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/fertilizer_agent_db
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:5.0
    container_name: fertilizer_mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
